= Getting Started with Teradata Vantage on Your Local Machine Using VirtualBox
:page-author: Adam Tworkiewicz
:page-email: adam.tworkiewicz@teradata.com
:page-revdate: September 7th, 2021
:description: Run Teradata Vantage express on your laptop using Virtualbox.
:keywords: data warehouses, compute storage separation, teradata, vantage, cloud data platform, object storage, business intelligence, enterprise analytics
:tabs:

include::partial$getting.started.intro.adoc[]

include::partial$getting.started.prereqs.adoc[]

== Installation

=== Download required software

. link:https://downloads.teradata.com/download/database/teradata-express-for-vmware-player[Teradata Express for VMware Player]. If you have not used the Teradata downloads website before, you will need to link:https://downloads.teradata.com/user/register[register].
. link:https://www.virtualbox.org/wiki/Downloads[VirtualBox].
+
NOTE: You can also install VirtualBox using `brew` and other package managers.

=== Run installers

Install VirtualBox by running the installer and accepting the default values. VirtualBox includes functionality that requires elevated privileges. When you start VirtualBox for the first time, you will be asked to confirm these elevated access. You will also need to reboot your machine to activate a VirtualBox kernel plugin.

=== Run Teradata Vantage Express

. Go to the directory where you downloaded Teradata Vantage Express and unzip the downloaded file.
. Set env variable `DISK_DIR` to the path of the unzipped image directory. Also, set `VM_NAME` to name the VM. For example:
+
[tabs]
====
MacOS::
+
--
[source, bash]
----
export DISK_DIR="$HOME/Downloads/VantageExpress17.10_Sles12"
export VM_NAME='Vantage Express 17.10'
----
--
Windows::
+
--
[source, powershell]
----
$env:DISK_DIR = "$HOME\Downloads"
$env:VM_NAME = "Vantage Express 17.10"
----
--
Linux::
+
--
[source, bash]
----
export DISK_DIR="$HOME/Downloads/VantageExpress17.10_Sles12"
export VM_NAME='Vantage Express 17.10'
----
--
====
. We will now create a VirtualBox VM that uses the downloaded image. Run the following command. The script will take several minutes to complete. During the execution, the script will ask for a password to login to the VM and perform some setup. The password is `root`.
+
[tabs]
====
MacOS::
+
--
[source, bash]
----
bash -c "$(curl -fsSL https://git.io/Jz7rX)"
----
--
Windows::
+
--
[source, powershell]
----
iex ((New-Object System.Net.WebClient).DownloadString('https://git.io/Jz7rd'))
----
--
Linux::
+
--
[source, bash]
----
bash -c "$(curl -fsSL https://git.io/Jz7rX)"
----
--
====

include::partial$run.vantage.adoc[]

=== Run sample queries

include::partial$running.sample.queries.adoc[]

include::partial$getting.started.summary.adoc[]

include::partial$next.steps.adoc[]

== Further reading
* link:https://docs.teradata.com/r/KEoAHNnh~EbZLtVJNRo0Sg/root[Teradata® Studio™ and Studio™ Express Installation Guide]
