= Run Vantage Express on VMware
:page-author: Adam Tworkiewicz
:page-email: adam.tworkiewicz@teradata.com
:page-revdate: January 9th, 2023
:description: Run Vantage Express on your laptop using VMware.
:keywords: data warehouses, compute storage separation, teradata, vantage, cloud data platform, object storage, business intelligence, enterprise analytics
:icons: font

include::partial$getting.started.intro.adoc[]

== Prerequisites

. A computer using one of the following operating systems: Windows, Linux or Intel-based MacOS.
+
NOTE: For M1/M2 MacOS systems, see xref:getting.started.utm.adoc[].
. 30GB of disk space and enough CPU and RAM to be able to dedicate at least one core and 6GB RAM to the virtual machine.
. Admin rights to be able to install and run the software.
+
// NOTE: No admin rights on your local machine? No problem! Have a look at how to run Vantage Express in link:#[AWS], link:#[Azure], link:#[Google Cloud].

== Installation

=== Download required software

. The latest version of link:https://downloads.teradata.com/download/database/teradata-express-for-vmware-player[Vantage Express]. If you have not used the Teradata downloads website before, you will need to register.
. link:https://www.vmware.com/products/workstation-player.html[VMware Workstation Player].
+
IMPORTANT: Commercial organizations require commercial licenses to use VMware Workstation Player. If you don't want to acquire VMware licenses you can run Vantage Express on xref:getting.started.vbox.adoc[VirtualBox].
+
IMPORTANT: VMware doesn't offer VMware Workstation Player for MacOS. If you are on a Mac, you will need to install link:https://www.vmware.com/products/fusion/fusion-evaluation.html[VMware Fusion] instead. It's a paid product but VMware offers a free 30-day trial. Alternatively, you can run Vantage Express on xref:getting.started.vbox.adoc[VirtualBox] or xref:getting.started.utm.adoc[UTM].
. On Windows, you will also need link:https://www.7-zip.org/download.html[7zip] to unzip Vantage Express.

=== Run installers

. Install VMware Player or VMware Fusion by running the installer and accepting the default values.
. If on Windows, install `7zip`.

=== Run Vantage Express

. Go to the directory where you downloaded Vantage Express and unzip the downloaded file.
. Double-click on the `.vmx` file. This will start the VM image in VMware Player/Fusion.
include::partial$run.vantage.adoc[]

=== Run sample queries

. We will now run some queries in the VM. To avoid copy/paste issues between the host and the VM, we will open this quick start in the VM. Go to the virtual desktop, start Firefox and point it to this quick start.

include::partial$running.sample.queries.adoc[]

include::partial$getting.started.summary.adoc[]

include::partial$next.steps.adoc[]

== Further reading
* link:https://docs.teradata.com/r/Teradata-StudioTM-and-StudioTM-Express-Installation-Guide-17.20[Teradata® Studio™ and Studio™ Express Installation Guide]

include::ROOT:partial$community_link.adoc[]