= Getting Started with Teradata Vantage on Your Local Machine Using VirtualBox
:page-author: Adam Tworkiewicz
:page-email: adam.tworkiewicz@teradata.com
:page-revdate: September 7th, 2021
:description: Run Teradata Vantage express on your laptop using Virtualbox.
:keywords: data warehouses, compute storage separation, teradata, vantage, cloud data platform, object storage, business intelligence, enterprise analytics

include::partial$getting.started.intro.adoc[]

include::partial$getting.started.prereqs.adoc[]

== Installation

=== Download required software

. link:https://downloads.teradata.com/download/database/teradata-express-for-vmware-player[Teradata Express for VMware Player]. If you have not used the Teradata downloads website before, you will need to link:https://downloads.teradata.com/user/register[register].
. link:https://www.virtualbox.org/wiki/Downloads[VirtualBox].
+
NOTE: You can also install VirtualBox using `brew` and other package managers.

=== Run installers

Install VirtualBox by running the installer and accepting the default values. VirtualBox includes functionality that requires elevated privileges. When you start VirtualBox for the first time, you will be asked to confirm these elevated access. You will also need to reboot your machine to activate a VirtualBox kernel plugin.

=== Run Teradata Vantage Express

. Go to the directory where you downloaded Teradata Vantage Express and unzip the downloaded file.
. We will now create a VirtualBox VM that uses the downloaded image. Replace `DISK_DIR` value with the path to the unzipped image directory and execute the commands:
+
[source, bash]
----
export DISK_DIR="$HOME/Downloads/VantageExpress17.10_Sles12"

export VM_NAME='Vantage Express 17.10'
vboxmanage createvm --name "$VM_NAME" --register --ostype openSUSE_64
vboxmanage modifyvm "$VM_NAME" --ioapic on --memory 6000 --vram 128 --nic1 nat --graphicscontroller vmsvga --usb on --mouse usbtablet --clipboard-mode bidirectional
vboxmanage storagectl "$VM_NAME" --name "SATA Controller" --add sata --controller IntelAhci
vboxmanage storageattach "$VM_NAME" --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium  "$(find $DISK_DIR -name '*disk1*')"
vboxmanage storageattach "$VM_NAME" --storagectl "SATA Controller" --port 1 --device 0 --type hdd --medium  "$(find $DISK_DIR -name '*disk2*')"
vboxmanage storageattach "$VM_NAME" --storagectl "SATA Controller" --port 2 --device 0 --type hdd --medium  "$(find $DISK_DIR -name '*disk3*')"
vboxmanage storagectl "$VM_NAME" --name IDE --add ide

vboxmanage storageattach "$VM_NAME" --storagectl "SATA Controller" --port 3 --type dvddrive --medium $(vboxmanage list dvds | grep UUID | cut -d" " -f 3- | sed -e 's/^[[:space:]]*//' )
vboxmanage modifyvm "$VM_NAME" --natpf1 "tdssh,tcp,,4422,,22"
vboxmanage startvm "$VM_NAME" --type headless

n=1
until [ "$n" -ge 10 ]
do
  echo "Attempting to ssh into the vm. Attempt $n"
  ssh -p 4422 -o StrictHostKeyChecking=no root@localhost 'mount /dev/cdrom /media/dvd; /media/dvd/VBoxLinuxAdditions.run; echo $?' && break
  n=$((n+1))
  sleep 10
done

vboxmanage controlvm "$VM_NAME" acpipowerbutton

until [ "$n" -ge 10 ]
do
  echo "Checking if the vm is still running. Attempt $n"
  vboxmanage showvminfo "$VM_NAME" | grep -c "running" | grep 0 && break
  n=$((n+1))
  sleep 10
done
vboxmanage startvm "$VM_NAME"
----

include::partial$run.vantage.adoc[]

=== Run sample queries

include::partial$running.sample.queries.adoc[]

include::partial$getting.started.summary.adoc[]

include::partial$next.steps.adoc[]

== Further reading
* link:https://docs.teradata.com/r/KEoAHNnh~EbZLtVJNRo0Sg/root[Teradata® Studio™ and Studio™ Express Installation Guide]
