= Run Vantage Express on VirtualBox
:page-author: Adam Tworkiewicz
:page-email: adam.tworkiewicz@teradata.com
:page-revdate: September 7th, 2021
:description: Run Teradata Vantage express on your laptop using Virtualbox.
:keywords: data warehouses, compute storage separation, teradata, vantage, cloud data platform, object storage, business intelligence, enterprise analytics
:tabs:

include::partial$getting.started.intro.adoc[]

== Prerequisites

. A computer using one of the following operating systems: Windows 10, Linux or MacOS.
. 30GB of disk space and enough CPU and RAM to be able to dedicate at least one core and 6GB RAM to the virtual machine.
. Admin rights to be able to install and run the software.
+
// NOTE: No admin rights on your local machine? No problem! Have a look at how to run Vantage Express in link:#[AWS], link:#[Azure], link:#[GCP].

== Installation

=== Download required software

. link:https://downloads.teradata.com/download/database/teradata-express-for-vmware-player[Vantage Express] VM image. The download package is called __"Vantage Express for VMware Player"__ but don't worry, it will work with VirtualBox.
+
NOTE: If you have not used the Teradata downloads website before, you will need to register first.
. link:https://www.virtualbox.org/wiki/Downloads[VirtualBox], version 6.1.
+
NOTE: You can also install VirtualBox using `brew` and other package managers.
. On Windows, you will also need link:https://www.7-zip.org/download.html[7zip] to unzip Vantage Express.

=== Run installers

. Install VirtualBox by running the installer and accepting the default values. VirtualBox includes functionality that requires elevated privileges. When you start VirtualBox for the first time, you will be asked to confirm these elevated access. You will also need to reboot your machine to activate a VirtualBox kernel plugin.
. If on Windows, install `7zip`.

=== Run Vantage Express

. Go to the directory where you downloaded Teradata Vantage Express and unzip the downloaded file.
. Set env variable `VM_IMAGE_DIR` to the path of the unzipped image directory. For example:
+
[tabs]
====
Windows::
+
--
Run in Powershell as Administrator:
[source, powershell, role="content-editable"]
----
$env:VM_IMAGE_DIR = "$HOME\Downloads\VantageExpress17.10_Sles12"
----
--
MacOS::
+
--
[source, bash, role="content-editable"]
----
export VM_IMAGE_DIR="$HOME/Downloads/VantageExpress17.10_Sles12"
----
--
Linux::
+
--
[source, bash, role="content-editable"]
----
export VM_IMAGE_DIR="$HOME/Downloads/VantageExpress17.10_Sles12"
----
--
====
. We will now create a VirtualBox VM that uses the downloaded image. Run the following command. The script will take several minutes to complete. During the execution, the script will ask for a password to login to the VM and perform some setup. The password is `root`.
+
[tabs]
====
Windows::
+
--
Continue in the same Powershell as Administrator:
[source, powershell]
----
iex ((New-Object System.Net.WebClient).DownloadString('https://git.io/Jz7rd'))
----
--
MacOS::
+
--
[source, bash]
----
bash -c "$(curl -fsSL https://git.io/Jz7rX)"
----
--
Linux::
+
--
[source, bash]
----
bash -c "$(curl -fsSL https://git.io/Jz7rX)"
----
--
====

include::partial$run.vantage.adoc[]

=== Run sample queries

include::partial$running.sample.queries.adoc[]

include::partial$getting.started.summary.adoc[]

include::partial$next.steps.adoc[]

== Further reading
* link:https://docs.teradata.com/r/KEoAHNnh~EbZLtVJNRo0Sg/root[Teradata® Studio™ and Studio™ Express Installation Guide]
