= Connect to Vantage using JDBC
:experimental:
:page-author: Adam Tworkiewicz
:page-email: adam.tworkiewicz@teradata.com
:page-revdate: September 8th, 2021
:description: How to connect to Teradata Vantage using JDBC
:keywords: data warehouses, compute storage separation, teradata, vantage, cloud data platform, JDBC, java applications, business intelligence, enterprise analytics

== Overview

This quick start demonstrates how to connect to Teradata Vantage using JDBC. We will go through a sample JDBC project. The entire project is published in GitHub at link:https://github.com/Teradata/jdbc-sample-app[].

== Prerequsites

* Access to a Teradata Vantage instance.
+
include::ROOT:partial$vantage.express.options.adoc[]
* JDK
* Maven

== Install the driver

1. Go to link:https://downloads.teradata.com/download/connectivity/jdbc-driver[the Teradata JDBC download page] and download the driver (you can choose zip or tar). The website will ask you to login (if you don't have an account you will need to register first) and accept the license before you download the file.
2. Unzip the driver.
3. Add the driver to your local Maven repository:
+
[source, bash, id="jdbc_first_config", role="content-editable emits-gtm-events"]
----
mvn install:install-file \
   -Dfile=terajdbc4.jar \
   -DgroupId=com.teradata \
   -DartifactId=terajdbc4 \
   -Dversion=17.10.00.26 \
   -Dpackaging=jar \
   -DgeneratePom=true
----

== Add dependency to your maven project

Now that we have the jar in the local repository, we can reference the jar as a dependency in our Maven pom:

++++
<script src="https://emgithub.com/embed.js?target=https%3A%2F%2Fgithub.com%2FTeradata%2Fjdbc-sample-app%2Fblob%2Fmain%2Fpom.xml%23L22-L26&style=github&showBorder=on&showLineNumbers=on&showFileMeta=on&showCopy=on&fetchFromJsDelivr=on"></script>
++++

== Code to send a query

NOTE: This step assumes that your Vantage database is available on `localhost` on port `1025`. If you are running Vantage Express on your laptop, you need to expose the port from the VM to the host machine. Refer to your virtualization software documentation how to forward ports.

The project is set up. All that is left, is to load the driver, pass connection and authentication parameters and run a query:

++++
<script src="https://emgithub.com/embed.js?target=https%3A%2F%2Fgithub.com%2FTeradata%2Fjdbc-sample-app%2Fblob%2Fmain%2Fsrc%2Fmain%2Fjava%2Fcom%2Fteradata%2Fapp%2FApp.java&style=github&showBorder=on&showLineNumbers=on&showFileMeta=on&showCopy=on"></script>
++++

== Summary

In this quick start we have learned how to connect to Teradata Vantage using JDBC. We went through the process of installing the latest JDBC driver and later used it in a Java application with Maven as the build tool.

== Further reading
* link:https://teradata-docs.s3.amazonaws.com/doc/connectivity/jdbc/reference/current/frameset.html[Teradata JDBC Driver Reference]
