= Connect to Vantage using JDBC
:experimental:
:page-author: Adam Tworkiewicz
:page-email: adam.tworkiewicz@teradata.com
:page-revdate: November 14th, 2022
:description: How to connect to Teradata Vantage using JDBC
:keywords: data warehouses, compute storage separation, teradata, vantage, cloud data platform, JDBC, java applications, business intelligence, enterprise analytics

== Overview

This how-to demonstrates how to connect to Teradata Vantage using JDBC using a sample Java application: link:https://github.com/Teradata/jdbc-sample-app[].

== Prerequisites

* Access to a Teradata Vantage instance.
+
include::ROOT:partial$vantage_clearscape_analytics.adoc[]
* JDK
* Maven

== Add dependency to your maven project

Add the Teradata JDBC driver as a dependency to your Maven POM XML file:

++++
<script src="https://emgithub.com/embed-v2.js?target=https%3A%2F%2Fgithub.com%2FTeradata%2Fjdbc-sample-app%2Fblob%2Fmain%2Fpom.xml%23L109-L113&style=github&type=code&showBorder=on&showLineNumbers=on&showFileMeta=on&showFullPath=on&showCopy=on&fetchFromJsDelivr=on"></script>
++++

== Code to send a query

NOTE: This step assumes that your Vantage database is available on `localhost` on port `1025`. If you are running Vantage Express on your laptop, you need to expose the port from the VM to the host machine. Refer to your virtualization software documentation how to forward ports.

The project is set up. All that is left, is to load the driver, pass connection and authentication parameters and run a query:

++++
<script src="https://emgithub.com/embed-v2.js?target=https%3A%2F%2Fgithub.com%2FTeradata%2Fjdbc-sample-app%2Fblob%2Fmain%2Fsrc%2Fmain%2Fjava%2Fcom%2Fteradata%2Fapp%2FApp.java%23L1-L51&style=github&type=code&showBorder=on&showLineNumbers=on&showFileMeta=on&showFullPath=on&showCopy=on&fetchFromJsDelivr=on"></script>
++++

== Run the tests

Run the tests:

[source, bash, id="run_mvn", role="content-editable emits-gtm-events"]
----
mvn test
----

== Summary

This how-to demonstrated how to connect to Teradata Vantage using JDBC. It described a sample Java application with Maven as the build tool that uses the Teradata JDBC driver to send SQL queries to Teradata Vantage.

== Further reading
* link:https://teradata-docs.s3.amazonaws.com/doc/connectivity/jdbc/reference/current/frameset.html[Teradata JDBC Driver Reference]

include::ROOT:partial$community_link.adoc[]