= Create Parquet File in NOS
:experimental:
:page-author: Obed Vega
:page-email: obed.vega@teradata.com
:page-revdate: August 2nd, 2021
:description: Teradata Vantage Native Object Storage - read and write from/to object storage, unified SQL interface for Vantage and object storage.
:keywords: data warehouses, compute storage separation, Teradata, vantage, cloud data platform, object storage, business intelligence, enterprise analytics

== Overview
Native Object Storage (NOS) is a Vantage feature that allows you to query data stored in files such as CSV, JSON, and Parquet format datasets. 
These datasets are located on external S3-compatible object storage such as AWS S3, Google GCS, Azure Blob or on-prem implementations. 
It's useful in scenarios where you want to explore data without building a data pipeline to bring it into Vantage.

== Prerequisites

You need access to a Teradata Vantage instance. NOS is enabled in all Vantage editions from Vantage Express through Developer, DYI to Vantage as a Service starting from version 17.10.

IMPORTANT: This tutorial is based on a s3 aws object storage. The bucket is at https://td-usgs-public.s3.amazonaws.com/. This bucket contains river flow data collected by the U.S. Geological Survey. Don't forget to use your own s3 storage and bucket.

include::ROOT:partial$vantage.express.options.adoc[]

== Create parquet with WRITE_NOS
NOTE: WRITE_NOS allows you to extract selected or all columns from a database table or from derived results and write to external object storage, such as Amazon S3, Azure Blob storage, Azure Data Lake Storage Gen2, and Google Cloud Storage. This functionality stores data in Parquet format.

You can find more documentation about WRITE_NOS functionality in the following link:

NOTE: https://docs.teradata.com/r/Teradata-VantageTM-Native-Object-Store-Getting-Started-Guide/January-2021/Writing-Data-to-External-Object-Store.

Assuming you already have a database created. 
If you haven't you can create a database with the following sintaxis: 
[source, teradata-sql]
----
CREATE USER db AS PERM=10e7, PASSWORD=db; 
----

Don't forget to give the proper access rights:
[source, teradata-sql]
----
GRANT EXECUTE FUNCTION on TD_SYSFNLIB.READ_NOS to db;
GRANT EXECUTE FUNCTION on TD_SYSFNLIB.WRITE_NOS to db;
----

You can also check the following link: https://docs.teradata.com/r/Teradata-VantageTM-Native-Object-Store-Getting-Started-Guide/January-2021/Writing-Data-to-External-Object-Store/Setting-Up-WRITE_NOS/Setting-Up-a-User-and-Privileges

1.- Let's first create a table on your Teradata Vantage instance: 

[source, teradata-sql]
----
CREATE SET TABLE db.parquet_table ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      column1 SMALLINT NOT NULL,
      column2 DATE FORMAT 'YY/MM/DD' NOT NULL,
      column3 DECIMAL(10,2))
PRIMARY INDEX ( column1 );
----

2.- Populate your table with some data: 

[source, teradata-sql]
----
INSERT INTO db.parquet_table (1,'2022/01/01',1.1);    
INSERT INTO db.parquet_table (2,'2022/01/02',2.2);
INSERT INTO db.parquet_table (3,'2022/01/03',3.3);
----

Your table should look something like this: 
----
column1   column2       column3
-------  --------  ------------
      1  22/01/01          1.10
      2  22/01/02          2.20
      3  22/01/03          3.30
----


3.- Create the parquet file with WRITE_NOS, don't forget to change the name of your s3 bucket:

NOTE: Add the proper Access_ID and Access_Key:

[source, teradata-sql]
----
SELECT * FROM WRITE_NOS (
ON ( SELECT * FROM db.parquet_table)
USING
LOCATION('/s3/td-usgs-public.s3.amazonaws.com/"bucket_name"/parquet_file_on_NOS.parquet/')
AUTHORIZATION('{"ACCESS_ID":"YOUR-ACCESS-KEY-ID",
"ACCESS_KEY":"YOUR-SECRET-ACCESS-KEY"}')
STOREDAS('PARQUET')
MAXOBJECTSIZE('16MB')
COMPRESSION('SNAPPY')
INCLUDE_ORDERING('TRUE')
INCLUDE_HASHBY('TRUE')
) as d;
----

NOTE: Now you have created the parquet file on your NOS s3 bucket. Now to easily query your file you need to follow step number 4.

4.- Create nos table:

NOTE: Assuming we have an authorization object for READ_NOS to access the external storage you are reading from, if not already done. For example, create an authorization object to the public object store, which does not require an id or key, so USER and PASSWORD are empty strings:

[source, teradata-sql]
----
CREATE AUTHORIZATION CEPH_AUTH
AS DEFINER TRUSTED
USER ''
PASSWORD '';
----

Don't forget to change the name of your bucket.

[source, teradata-sql]
----
CREATE MULTISET FOREIGN TABLE db.parquet_table_to_read_file_on_NOS
, EXTERNAL SECURITY DEFINER TRUSTED CEPH_AUTH,
MAP = TD_MAP1
(
  Location VARCHAR(2048) CHARACTER SET UNICODE CASESPECIFIC
  , col1 SMALLINT
  , col2 DATE 
  , col3 DECIMAL(10,2)

)
USING (
    LOCATION ('/s3/td-usgs-public.s3.amazonaws.com/"bucket_name"/parquet_file_on_NOS.parquet')
    STOREDAS ('PARQUET')
)NO PRIMARY INDEX;
----

5.- Now you are ready to Query your parquet file on NOS, let's try the following query:
[source, teradata-sql]
----
SELECT col1, col2, col3 FROM db.parquet_table_to_read_file_on_NOS;
----

Your data on the parquet file should look something like this:
----
  col1      col2          col3
------  --------  ------------
     1  22/01/01          1.10
     2  22/01/02          2.20
     3  22/01/03          3.30
----

== Summary

In this quick start we have learned how to create a parquet file with data on object storage using Native Object Storage (NOS) functionality in Vantage. NOS supports reading and importing data stored in CSV, JSON and Parquet formats. NOS can also export data from Vantage to object storage.

== Further reading
* link:https://docs.teradata.com/r/Teradata-VantageTM-Native-Object-Store-Getting-Started-Guide/January-2021/Writing-Data-to-External-Object-Store[Teradata Vantage™ - Writing Data to External Object Store]