= Query Service Quick Start Guide
:experimental:
:page-author: Sudha vedula
:page-email: sudha.vedula@teradata.com
:page-revdate: October 27th, 2022
:description: Teradata® Query Service is a middleware that provides REST APIs for relational Databases, including Teradata Database, Aster, and Hive.
:keywords: query service, teradata, vantage, query,

== Overview

Query Service provides APIs to:

.   Configure Teradata-supported systems
.	Submit SQL queries and access responses
.	Create database sessions
.	Access database and object metadata

This quickstart guide provides you examples for invoking REST API's using cURL.

== Prerequisites

Before you start, make sure:

.	Query Service is installed and configured . See link:https://docs.teradata.com/r/Teradata-Query-Service-Installation-Configuration-and-Usage-Guide-for-Customers/April-2022[Query Service ICU Guide]
.	The required authorization to connect to Database.

== Query Service API Examples

==== Connect to QueryService node using Basic Auth

Run the following cURL command to connect to QueryService node using BasicAuth by replacing QS_HOSTNAME, systemName, DB username and password .

----
curl -k -X GET 'https://<QS_HOSTNAME>::1443/systems/<systemName>/queries' \
--header 'Authorization: Basic YWRtaW46VGVyYWRhdGEyQA=='
----

==== How do I add a Teradata System?

Run the following cURL command to add a system by replacing QS_HOSTNAME, systemName and ADMIN_TOKEN along with system info.
----
curl -k -X PUT 'https://<QS_HOSTNAME>:1443/systems/<systemName>' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <ADMIN_TOKEN>' \
--data-raw '{
    "default_char_set": "ASCII",
    "default_database": "dbc",
    "default_transaction_mode": "DEFAULT",
    "log_mech": "DEFAULT",
    "host": "prometheus.td.teradata.com",
    "system_id": "prometheus.td.teradata.com",
    "system_type": "TERADATA"
}'

----

==== How do I make a simple API request?

Fetch all systems using the following cURL command by replacing QS_HOSTNAME and TOKEN.

----
curl -k -X GET "https://<QS_HOSTNAME>:1443/systems/"
-H "Accept:application/json"
-H "Authorization:Bearer $TOKEN"
----

==== What makes up this API request?
In this previous request,

. We are providing token to be authenticated.
. Using GET to fetch all systems.
. Response content will be json.

== Next Steps
You have now successfully completed the basic tasks required to use Query Service.
You can now do

== Resources
Refer to the link:https://docs.teradata.com/r/Teradata-Query-Service-Installation-Configuration-and-Usage-Guide-for-Customers/April-2022[Query Service Installation, Configuration, and Usage Guide]
 to explore the full potential of Query Service, and experiment with examples.
