= Time Series Analysis [WIP]
:experimental:
:page-author: Adam Tworkiewicz
:page-email: adam.tworkiewicz@teradata.com
:page-revdate: September 7th, 2021
:description: Time Series Analysis
:keywords: data warehouses, analytics, teradata, vantage, time series, business intelligence, enterprise analytics

== Overview

Time series is series of data points indexed in time order. It is data continuously produced and collected by a wide range of applications and devices including but not limited to Internet of Things. Teradata Vantage offers various functionalities to simplify time series data analysis. 

== Prerequisites

You need access to a Teradata Vantage instance. Times series functionalities and NOS are enabled in all Vantage editions from Vantage Express through Developer, DYI to Vantage as a Service starting from version 17.10. If you need a new instance of Vantage, you can install Vantage Express on your local machine using xref:getting.started.vmware.adoc[VMware], xref:getting.started.vbox.adoc[VirtualBox], or xref:getting.started.utm.adoc[UTM]. You can also run xref:vantage.express.gcp.adoc[Vantage Express in the cloud on GCP].

== Import data sets from AWS S3 using Vantage NOS

Our sample data sets are available on S3 bucket and can be accessed from Vantage directly using Vantage NOS. Data is in CSV foramt and let's ingest them into Vantage for our time series analysis. The bucket is at https://td-usgs-public.s3.amazonaws.com/.

Let's have a look at the data first. Below query will fetch the first 10 rows from S3 bucket.

[source, teradata-sql]
----
SELECT TOP 10 * FROM (
	LOCATION='/s3/td-usgs-public.s3.amazonaws.com/NYCTaxtTrip/'
) AS d;
----

Here is what we've got:

----

medallion               		hack_license				vendor_id	rate_code	store_and_fwd_flag	pickup_datetime		        dropoff_datetime		passenger_count		trip_time_in_secs	trip_distance	pickup_longitude	pickup_latitude	  dropoff_longitude	dropoff_latitude
---------------------------------	---------------------------------	---------	---------	------------------	-------------------------	-------------------------	---------------		-----------------	-------------	----------------	---------------	  -----------------	-----------------
C9E0259672E6F6677BA3EAE04511A7A0	2AB5F641A6BE8445CBAA25C34C10D498	CMT		1		N			2013-11-10T00:20:50.000Z	2013-11-10T00:47:22.000Z	1			1591                    3.6             -73.959595              40.718086         -73.983337            40.730938
C9E0259672E6F6677BA3EAE04511A7A0	2AB5F641A6BE8445CBAA25C34C10D498	CMT		1		N			2013-11-10T01:15:19.000Z	2013-11-10T01:24:07.000Z	1			528                     3.7             -73.972588              40.743603         -73.997002            40.714806
C9E0259672E6F6677BA3EAE04511A7A0	2AB5F641A6BE8445CBAA25C34C10D498	CMT		1		N			2013-11-10T01:30:09.000Z	2013-11-10T01:37:42.000Z	1			453                     2.0             -73.998352              40.721233         -73.99115             40.74461
C9E0259672E6F6677BA3EAE04511A7A0	2AB5F641A6BE8445CBAA25C34C10D498	CMT		1		N			2013-11-10T01:38:23.000Z	2013-11-10T01:45:09.000Z	1			406                     1.7             -73.991814              40.744537         -73.974815            40.75396
C9E0259672E6F6677BA3EAE04511A7A0	2AB5F641A6BE8445CBAA25C34C10D498	CMT		1		N			2013-11-10T01:57:49.000Z	2013-11-10T02:10:20.000Z	1			750                     2.4             -73.977859              40.725471         -73.987297            40.749561
C9E0259672E6F6677BA3EAE04511A7A0	2AB5F641A6BE8445CBAA25C34C10D498	CMT		1		N			2013-11-10T02:21:14.000Z	2013-11-10T02:33:51.000Z	1			757                     3.5             -74.005219              40.741226         -73.964577            40.764809
C9E0259672E6F6677BA3EAE04511A7A0	2AB5F641A6BE8445CBAA25C34C10D498	CMT		1		N			2013-11-10T01:51:03.000Z	2013-11-10T01:53:56.000Z	1			172                     0.5             -73.985451              40.735867         -73.977806            40.734016
C9E0259672E6F6677BA3EAE04511A7A0	2AB5F641A6BE8445CBAA25C34C10D498	CMT		1		N			2013-11-10T01:00:43.000Z	2013-11-10T01:05:10.000Z	1			266                     1.2             -73.794418              40.657249         -73.973907            40.747341
C9E0259672E6F6677BA3EAE04511A7A0	2AB5F641A6BE8445CBAA25C34C10D498	CMT		1		N			2013-11-10T00:13:45.000Z	2013-11-10T00:17:18.000Z	1			213                     0.5             -73.953896              40.712482         -73.956383            40.717175
C9E0259672E6F6677BA3EAE04511A7A0	2AB5F641A6BE8445CBAA25C34C10D498	CMT		1		N			2013-11-09T23:52:54.000Z	2013-11-10T00:04:44.000Z	1			710                     1.8             -73.965065              40.714432         -73.952423            40.69487

----

Let's extract the complete data and bring it into Vantage for further analysis.

[source, teradata-sql]
----

CREATE TABLE trip 
( 
  medallion varchar(50) character set latin NOT casespecific,
  hack_license varchar(50) character set latin NOT casespecific,
  vendor_id varchar(10) character set latin NOT casespecific,
  rate_code          integer,
  store_and_fwd_flag char(1) character set latin NOT casespecific,
  pickup_datetime timestamp(6),
  dropoff_datetime timestamp(6),
  passenger_count   smallint,
  trip_time_in_secs integer,
  trip_distance float,
  pickup_longitude float,
  pickup_latitude float,
  dropoff_longitude float,
  dropoff_latitude float
) 
PRIMARY INDEX ( medallion );


INSERT INTO trip 
SELECT * FROM (
	LOCATION='/s3/td-usgs-public.s3.amazonaws.com/NYCTaxtTrip/'
) AS d;

----

Result:

----
480535 rows affected.
----

Vantage will now fetch the data from S3 and insert into trip table we just created. 

== Basic time series operations

Now that we are familiar with the data set, we can use Vantage capabilities to quickly analyse the data set. First, let's identify how many passengers are being picked up by hour in the month of November. 

[source, teradata-sql]
----
SELECT TOP 10
$TD_TIMECODE_RANGE 
,begin($TD_TIMECODE_RANGE) time_bucket_start --(timestamp, format 'YYYY-MM-DDBHH:MI:SS') time_bucket_start
,sum(passenger_count) passenger_count
FROM trip 
WHERE extract(month from pickup_datetime)=11
GROUP BY TIME(HOURS(1))
USING TIMECODE(pickup_datetime)
ORDER BY 1;
----

Result:

----
TIMECODE_RANGE	                                                          time_bucket_start                   passenger_count
-----------------------------------------------------------------         --------------------------------    ------
2013-11-09 22:00:00.000000-05:00,2013-11-09 23:00:00.000000-05:00	  2013-11-09 22:00:00.000000-05:00    14
2013-11-09 23:00:00.000000-05:00,2013-11-10 00:00:00.000000-05:00	  2013-11-09 23:00:00.000000-05:00    13673
2013-11-10 00:00:00.000000-05:00,2013-11-10 01:00:00.000000-05:00	  2013-11-10 00:00:00.000000-05:00    58635
2013-11-10 01:00:00.000000-05:00,2013-11-10 02:00:00.000000-05:00	  2013-11-10 01:00:00.000000-05:00    51046
2013-11-10 02:00:00.000000-05:00,2013-11-10 03:00:00.000000-05:00	  2013-11-10 02:00:00.000000-05:00    44277
2013-11-10 03:00:00.000000-05:00,2013-11-10 04:00:00.000000-05:00	  2013-11-10 03:00:00.000000-05:00    34422
2013-11-10 04:00:00.000000-05:00,2013-11-10 05:00:00.000000-05:00	  2013-11-10 04:00:00.000000-05:00    22054
2013-11-10 05:00:00.000000-05:00,2013-11-10 06:00:00.000000-05:00	  2013-11-10 05:00:00.000000-05:00    9395
2013-11-10 06:00:00.000000-05:00,2013-11-10 07:00:00.000000-05:00	  2013-11-10 06:00:00.000000-05:00    7828
2013-11-10 07:00:00.000000-05:00,2013-11-10 08:00:00.000000-05:00	  2013-11-10 07:00:00.000000-05:00    10167

----

Yes, this can also be achieved by extracting the hour from time and then aggregating - it's additional code/work, but can be done without timeseries specific functionality. 

But, now let's go a step further to identify how many passengers are being picked up and what is the average trip duration by vendor every 15 minutes in November. 

[source, teradata-sql]
----
SELECT TOP 10
$TD_TIMECODE_RANGE 
,vendor_id
,sum(passenger_count)
,avg(trip_time_in_secs)
FROM TRNG_NYCTaxi.trip
GROUP BY TIME (MINUTES(15) and vendor_id)
USING TIMECODE(pickup_datetime)
WHERE extract(month from pickup_datetime)=11
ORDER BY 1,2;
----

Result:

----

TIMECODE_RANGE	                                                    vendor_id   passenger_count	  trip_time_in_secs
-----------------------------------------------------------------   -----       ---------------   -----------------
2013-11-09 22:15:00.000000-05:00,2013-11-09 22:30:00.000000-05:00   CMT	        1                 1344
2013-11-09 22:30:00.000000-05:00,2013-11-09 22:45:00.000000-05:00   CMT	        1                 5128
2013-11-09 22:45:00.000000-05:00,2013-11-09 23:00:00.000000-05:00   VTS	        12                4560
2013-11-09 23:00:00.000000-05:00,2013-11-09 23:15:00.000000-05:00   CMT	        15                3745.571429
2013-11-09 23:00:00.000000-05:00,2013-11-09 23:15:00.000000-05:00   VTS	        21                3425.454545
2013-11-09 23:15:00.000000-05:00,2013-11-09 23:30:00.000000-05:00   CMT	        91                2508.816667
2013-11-09 23:15:00.000000-05:00,2013-11-09 23:30:00.000000-05:00   VTS	        176               2572.142857
2013-11-09 23:30:00.000000-05:00,2013-11-09 23:45:00.000000-05:00   CMT	        931               1655.879661
2013-11-09 23:30:00.000000-05:00,2013-11-09 23:45:00.000000-05:00   VTS	        1360              1673.446154

----

This is the power of Vantage time series functionality. Without needing complicated, cumbersome logic we are able to find average trip duration by vendor every 15 minutes just by modifying the group by time clause. Lets now look at how simple it is to build moving averages based on this. Let us start by creating a view as below.

[source, teradata-sql]
----
REPLACE VIEW NYC_taxi_trip_ts as
SELECT
$TD_TIMECODE_RANGE time_bucket_per
,vendor_id
,sum(passenger_count) passenger_cnt
,sum(trip_time_in_secs) avg_trip_time_in_secs
FROM TRNG_NYCTaxi.trip 
GROUP BY TIME(MINUTES(15) and vendor_id)
USING TIMECODE(pickup_datetime)
WHERE extract(month from pickup_datetime)=11;
----

Let's calculate a 2 hours moving average on our 15-minutes time series. 2 hour is 8 * 15 minutes periods.

[source, teradata-sql]
----
SELECT TOP 10 * FROM MovingAverage (
  ON NYC_taxi_trip_ts PARTITION BY vendor_id ORDER BY time_bucket_per
  USING
  MAvgType ('S')
  WindowSize (8)
  TargetColumns ('passenger_cnt')
) AS dt 
WHERE begin(time_bucket_per)(date) = '2013-11-10'
ORDER BY vendor_id, time_bucket_per;
----


Result:

----

time_bucket_per	                                                      vendor_id	    passenger_cnt   avg_trip_time_in_secs   passenger_cnt_smavg
-----------------------------------------------------------------     ---------     -------------   ---------------------   -------------------
2013-11-10 00:15:00.000000-05:00,2013-11-10 00:30:00.000000-05:00     CMT           5949            3075511                 2187.625
2013-11-10 00:30:00.000000-05:00,2013-11-10 00:45:00.000000-05:00     CMT           5810            2918201                 2913.75
2013-11-10 00:45:00.000000-05:00,2013-11-10 01:00:00.000000-05:00     CMT           5566            2767533                 3609.375
2013-11-10 01:00:00.000000-05:00,2013-11-10 01:15:00.000000-05:00     CMT           5358            2676729                 4277.25
2013-11-10 01:15:00.000000-05:00,2013-11-10 01:30:00.000000-05:00     CMT           5133            2524393                 4907.5
2013-11-10 01:30:00.000000-05:00,2013-11-10 01:45:00.000000-05:00     CMT           4896            2411368                 5403.125
2013-11-10 01:45:00.000000-05:00,2013-11-10 02:00:00.000000-05:00     CMT           4815            2276216                 5448.75
2013-11-10 02:00:00.000000-05:00,2013-11-10 02:15:00.000000-05:00     CMT           4699            2267700                 5278.25
2013-11-10 02:15:00.000000-05:00,2013-11-10 02:30:00.000000-05:00     CMT           4505            2126760                 5097.75
2013-11-10 02:30:00.000000-05:00,2013-11-10 02:45:00.000000-05:00     CMT           4355            2031154                 4915.875

----

==== Note: 
In addition to above time series operations, Vantage also provides a special time series tables with Primary Time Index (PTI). These are regular Vantage tables with PTI defined rather than a Primary Index (PI). Though PTI tables are not mandatory for time series functionality/operations, PTI tables optimizes how the time series data is stored physically and hence improves performance considerably compared to regular tables. 

== Summary

In this quick start we have learnt how easy it is to analyse time series datasets using Vantage's time series capabilities. 

== Further reading
* link:https://docs.teradata.com/r/Teradata-VantageTM-Time-Series-Tables-and-Operations/July-2021/Introduction-to-Teradata-Time-Series-Tables-and-Operations[Teradata Vantage™ - Time Series Tables and Operations]
* link:https://docs.teradata.com/r/2mw8ooFr~xX0EaaGFaDW8A/root[Teradata Vantage™ - Native Object Store Getting Started Guide]
