= Run Vantage Express on Google Cloud
:page-author: Adam Tworkiewicz
:page-email: adam.tworkiewicz@teradata.com
:page-revdate: August 23rd, 2022
:description: Run Vantage Express on Google Cloud.
:keywords: data warehouses, compute storage separation, teradata, vantage, cloud data platform, object storage, business intelligence, enterprise analytics
:tabs:
:experimental:

== Overview

This how-to demonstrates how to run Vantage Express in Google Cloud Platform. Vantage Express contains a fully functional Teradata SQL Engine.

NOTE: If do not wish to pay for cloud usage you can install Vantage Express locally using link:getting.started.vmware.adoc[VMware], link:getting.started.vbox[VirtualBox], link:getting.started.utm[UTM].

== Prerequisites

. A Google Cloud account.
. `gcloud` command line utility installed on your machine. You can find installation instructions here: https://cloud.google.com/sdk/docs/install.


== Installation

. Create a Ubuntu VM with 4 CPU's and 8GB of RAM, a 70GB balanced disk. The following command creates a VM in `us-central1` region. For best performance, replace the  region with one that is the closest to you. For the list of supported regions see link:https://cloud.google.com/compute/docs/regions-zones[Google Cloud regions documentation].
+
[tabs]
====
Windows::
+
--
Run in Powershell:
[source, powershell, role="content-editable emits-gtm-events", id="gcloud_create_vm_win"]
----
gcloud compute instances create teradata-vantage-express `
  --zone=us-central1-a `
  --machine-type=n2-custom-4-8192 `
  --create-disk=boot=yes,device-name=ve-disk,image-project=ubuntu-os-cloud,image-family=ubuntu-2004-lts,size=70,type=pd-balanced `
  --enable-nested-virtualization `
  --tags=ve
----
--
MacOS::
+
--
[source, bash, role="content-editable emits-gtm-events", id="gcloud_create_vm_macos"]
----
gcloud compute instances create teradata-vantage-express \
  --zone=us-central1-a \
  --machine-type=n2-custom-4-8192 \
  --create-disk=boot=yes,device-name=ve-disk,image-project=ubuntu-os-cloud,image-family=ubuntu-2004-lts,size=70,type=pd-balanced \
  --enable-nested-virtualization \
  --tags=ve
----
--
Linux::
+
--
[source, bash, role="content-editable emits-gtm-events", id="gcloud_create_vm_linux"]
----
gcloud compute instances create teradata-vantage-express \
  --zone=us-central1-a \
  --machine-type=n2-custom-4-8192 \
  --create-disk=boot=yes,device-name=ve-disk,image-project=ubuntu-os-cloud,image-family=ubuntu-2004-lts,size=70,type=pd-balanced \
  --enable-nested-virtualization \
  --tags=ve
----
--
====
. ssh to your VM:
+
[source, bash, role="content-editable emits-gtm-events", id="gcloud_ssh"]
----
gcloud compute ssh teradata-vantage-express --zone=us-central1-a
----
. Switch to `root` user:
+
[source, bash, role="content-editable emits-gtm-events", id="sudo"]
----
sudo -i
----
. Prepare the download directory for Vantage Express:
+
[source, bash, role="content-editable emits-gtm-events", id="download_dir"]
----
mkdir /opt/downloads
cd /opt/downloads
----
include::partial$install.ve.in.public.cloud.adoc[]
* If you would like to connect to Vantage Express from the Internet, you will need to open up firewall holes to your VM. You should also change the default password to `dbc` user:
. To change the password for `dbc` user go to your VM and start bteq:
+
[source, bash, role="content-editable emits-gtm-events", id="pw_change_bteq"]
----
bteq
----
. Login to your database using `dbc` as username and password:
+
[source, teradata-sql, role="content-editable emits-gtm-events", id="pw_change_bteq_logon"]
----
.logon localhost/dbc
----
. Change the password for `dbc` user:
+
[source, teradata-sql, role="content-editable emits-gtm-events", id="pw_change_mod_user"]
----
MODIFY USER dbc AS PASSWORD = new_password;
----
. You can now open up port 1025 to the internet using gcloud command:
+
[source%prewrap, bash, role="content-editable emits-gtm-events", id="gcloud_fw_rule"]
----
gcloud compute firewall-rules create vantage-express --allow=tcp:1025 --direction=IN --target-tags=ve
----

== Cleanup

To stop incurring charges, delete the VM:
[source, bash, role="content-editable emits-gtm-events", id="delete_vm"]
----
gcloud compute instances delete teradata-vantage-express --zone=us-central1-a
----

Also, remember to remove any firewall rules that you have added, e.g.:
[source, bash, role="content-editable emits-gtm-events", id="delete_fw_rule"]
----
gcloud compute firewall-rules delete vantage-express
----

include::partial$next.steps.adoc[]

== Further reading
* link:https://docs.teradata.com/r/Teradata-StudioTM-and-StudioTM-Express-Installation-Guide-17.20[Teradata® Studio™ and Studio™ Express Installation Guide]
* link:https://docs.teradata.com/r/jmAxXLdiDu6NiyjT6hhk7g/root[Introduction to BTEQ]

