= Deploy CloudFormation Template from AWS CLI
:experimental:
:page-author: Thripti Aravind
:page-email: thripti.aravind@teradata.com
:page-revdate: November 14th, 2023
:description: Learn how to deploy Teradata AI Unlimited CloudFormation Template from AWS CLI.
:keywords: Teradata AI Unlimited, Teradata AI Unlimited Workspace service, Teradata AI Unlimited Compute Engine
:page-image-directory: deploy-ai-unlimited-awscli-cloudformation

IMPORTANT: This product is in preview and is subject to change. If you're interested in learning more about this offering, contact Teradata Support.

== Overview

You can deploy a stack using the `aws cloudformation create-stack` or `aws cloudformation deploy` commands from the AWS CLI. The example in this section uses the create-stack command. See link:https://docs.aws.amazon.com/cli/latest/reference/cloudformation/#cli-aws-cloudformation[AWS CLI Command Reference] documentation for the syntax differences between the `create-stack` and `deploy` commands.

== Before you start

* Install and configure AWS CLI. See link:https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html[Get started with the AWS CLI].
* Make sure you have:
** Required AWS credentials.
** Necessary IAM permissions to create and manage resources. If you do not have the necessary permissions, contact your organization administrator to create all the specified roles.
** Required parameter files and CloudFormation templates. You can download the files from the link:https://github.com/Teradata/ai-unlimited/tree/develop/deployments/aws[AI Unlimited GitHub repository].

== Create a stack
Run the following command on the AWS CLI:

[source, bash, id="aws_cli_create_stack", role="content-editable emits-gtm-events"]
----
aws cloudformation create-stack --stack-name all-in-one \
  --template-body file://all-in-one.yaml \
  --parameters file://test_parameters/all-in-one.json \
  --tags Key=ThisIsAKey,Value=AndThisIsAValue \
  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
----

NOTE: 

* CAPABILITY_IAM is required if IamRole is set to New.
* CAPABILITY_NAMED_IAM is required if IamRole is set to New and IamRoleName is given a value.

To use an existing role, see Control AWS Access and Permissions using Permissions and Policies.

== Delete a stack

Run the following command on the AWS CLI:

[source, bash, id="aws_cli_delete_stack", role="content-editable emits-gtm-events"]
----
aws cloudformation delete-stack --stack-name <stackname> 
----

== Get stack information

Run the following command on the AWS CLI:

[source, bash, id="aws_cli_get_stack_info", role="content-editable emits-gtm-events"]
----
aws cloudformation delete-stack --stack-name <stackname> 
aws cloudformation describe-stacks --stack-name <stackname> 
aws cloudformation describe-stack-events --stack-name <stackname> 
aws cloudformation describe-stack-instance --stack-name <stackname> 
aws cloudformation describe-stack-resource --stack-name <stackname> 
aws cloudformation describe-stack-resources --stack-name <stackname>
----
 
== Get stack outputs

Run the following command on the AWS CLI:

[source, bash, id="aws_cli_get_stack_output", role="content-editable emits-gtm-events"]
----
aws cloudformation describe-stacks --stack-name <stackname>  --query 'Stacks[0].Outputs' --output table
----

== Next steps

* Get started with Teradata AI Unlimited by running a simple workflow. See xref::running-sample-ai-unlimited-workload.adoc[].

* Interested in learning how Teradata AI Unlimited can help you with real-life use cases? Coming soon! Keep watching this space for the GitHub link.

include::ROOT:partial$community_link.adoc[]
