= Jupyterノートブックのデモ
:page-lang: ja
:description: Teradata Vantage をすぐに使いこなしましょう。機能について学習する。一般的なタスクの使い方を見つける。サンプル ソース コードを探索します。
:keywords: data warehouses, cloud data warehouse, compute storage separation, teradata, vantage, cloud data platform, java applications, business intelligence, enterprise analytics, hybrid multi-cloud, business outcomes
:page-jupyterbook: true

++++
    <div class="content landing">
      <div class="landing-container">
        <div class="tile-container">
          <div class="tile-section">
            <div class="tile-section-title" id="telco">通信</div>
            <div class="tile-section-container">
              <div class="tile">
                <a href="austin-bike-share.html">
                  <div class="link">
                    <div class="tile-title">スマートな廃止措置</div>
                    <div class="tile-content">AWS 上のクラウドで Teradata Vantage Express を 実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">通信</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="vantage.express.gcp.html">
                  <div class="link">
                    <div class="tile-title">よりスマートなネットワーク最適化</div>
                    <div class="tile-content">Google Cloud 上のクラウドで Teradata Vantage Express を実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">通信</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="run-vantage-express-on-microsoft-azure.html">
                  <div class="link">
                    <div class="tile-title">パーソナライゼーション</div>
                    <div class="tile-content">Microsoft Azure 上のクラウドで Teradata Vantage Express を実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">通信</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="getting.started.vmware.html">
                  <div class="link">
                    <div class="tile-title">関連する価格とプロモーション</div>
                    <div class="tile-content">開発およびテストのためにマシンに Teradata Vantage Express をインストールする方法を学びます。</div>
                    <div class="tile-tags">
                      <div class="tag">通信</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="getting.started.vbox.html">
                  <div class="link">
                    <div class="tile-title">接続されたサプライチェーン</div>
                    <div class="tile-content">VirtualBox を使用してローカル マシン上で Teradata Vantage Express を実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">通信</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="getting.started.utm.html">
                  <div class="link">
                    <div class="tile-title">よりスマートなネットワーク展開</div>
                    <div class="tile-content">UTM を使用して Mac 上で Teradata Vantage Express を実行する。Apple チップセットをサポート。</div>
                    <div class="tile-tags">
                      <div class="tag">通信</div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
            <div class="tile-section-title" id="automotive">自動車</div>
            <div class="tile-section-container">
              <div class="tile">
                <a href="run-vantage-express-on-aws.html">
                  <div class="link">
                    <div class="tile-title">コネクテッドな自動車イノベーション</div>
                    <div class="tile-content">Teradata Vantage Express を AWS のクラウドで実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">自動車</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="vantage.express.gcp.html">
                  <div class="link">
                    <div class="tile-title">スマートでコネクテッドな工場</div>
                    <div class="tile-content">Google Cloud 上のクラウドで Teradata Vantage Express を実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">自動車</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="run-vantage-express-on-microsoft-azure.html">
                  <div class="link">
                    <div class="tile-title">緻密な財務管理</div>
                    <div class="tile-content">Microsoft Azure 上のクラウドで Teradata Vantage Express を実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">自動車</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="getting.started.vmware.html">
                  <div class="link">
                    <div class="tile-title">回復力のあるサプライチェーン</div>
                    <div class="tile-content">開発およびテストのためにマシンに Teradata Vantage Express をインストールする方法を学びます。</div>
                    <div class="tile-tags">
                      <div class="tag">自動車</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="getting.started.vbox.html">
                  <div class="link">
                    <div class="tile-title">パーソナライズされた顧客エクスペリエンス</div>
                    <div class="tile-content">VirtualBox を使用してローカル マシン上で Teradata Vantage Express を実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">自動車</div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
            <div class="tile-section-title" id="healthcare">ヘルスケア</div>
            <div class="tile-section-container">
              <div class="tile">
                <a href="run-vantage-express-on-aws.html">
                  <div class="link">
                    <div class="tile-title">ケア提供のイノベーション</div>
                    <div class="tile-content">Teradata Vantage Express を AWS のクラウドで実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">ヘルスケア</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="vantage.express.gcp.html">
                  <div class="link">
                    <div class="tile-title">パフォーマンス管理</div>
                    <div class="tile-content">Google Cloud 上のクラウドで Teradata Vantage Express を実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">ヘルスケア</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="run-vantage-express-on-microsoft-azure.html">
                  <div class="link">
                    <div class="tile-title">新しい支払いモデル</div>
                    <div class="tile-content">Microsoft Azure 上のクラウドで Teradata Vantage Express を実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">ヘルスケア</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="getting.started.vmware.html">
                  <div class="link">
                    <div class="tile-title">適応型サプライチェーン</div>
                    <div class="tile-content">開発およびテストのためにマシンに Teradata Vantage Express をインストールする方法を学びます。</div>
                    <div class="tile-tags">
                      <div class="tag">ヘルスケア</div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
            <div class="tile-section-title" id="government">官公庁</div>
            <div class="tile-section-container">
              <div class="tile">
                <a href="run-vantage-express-on-aws.html">
                  <div class="link">
                    <div class="tile-title">市民サービス</div>
                    <div class="tile-content">Teradata Vantage Express を AWS のクラウドで実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">官公庁</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="vantage.express.gcp.html">
                  <div class="link">
                    <div class="tile-title">公衆衛生管理</div>
                    <div class="tile-content">Google Cloud 上のクラウドで Teradata Vantage Express を実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">官公庁</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="run-vantage-express-on-microsoft-azure.html">
                  <div class="link">
                    <div class="tile-title">政策決定</div>
                    <div class="tile-content">Microsoft Azure 上のクラウドで Teradata Vantage Express を実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">官公庁</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="getting.started.vmware.html">
                  <div class="link">
                    <div class="tile-title">不正防止</div>
                    <div class="tile-content">開発およびテストのためにマシンに Teradata Vantage Express をインストールする方法を学びます。</div>
                    <div class="tile-tags">
                      <div class="tag">官公庁</div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
            <div class="tile-section-title" id="retail">小売り</div>
            <div class="tile-section-container">
              <div class="tile">
                <a href="run-vantage-express-on-aws.html">
                  <div class="link">
                    <div class="tile-title">従業員管理</div>
                    <div class="tile-content">AWS のクラウドで Teradata Vantage Express を実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">小売り</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="vantage.express.gcp.html">
                  <div class="link">
                    <div class="tile-title">マーケティングと顧客体験</div>
                    <div class="tile-content">Google Cloud 上のクラウドで Teradata Vantage Express を実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">小売り</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="run-vantage-express-on-microsoft-azure.html">
                  <div class="link">
                    <div class="tile-title">デジタルストアと実店舗</div>
                    <div class="tile-content">Microsoft Azure 上のクラウドで Teradata Vantage Express を実行する。</div>
                    <div class="tile-tags">
                      <div class="tag">小売り</div>
                    </div>
                  </div>
                </a>
              </div>
              <div class="tile">
                <a href="getting.started.vmware.html">
                  <div class="link">
                    <div class="tile-title">カテゴリ管理</div>
                    <div class="tile-content">開発およびテストのためにマシンに Teradata Vantage Express をインストールする方法を学びます。</div>
                    <div class="tile-tags">
                      <div class="tag">小売り</div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div class="doc">
            <div class="admonitionblock question landing-page">
              <table>
                <tbody><tr>
                <td class="icon">
                <i class="fa icon-question"></i>探しているデモが見つかりませんでしたか?
                </td>
                <td class="content">
                 デモに貢献またはリクエストする
                </td>
                <td class="question-action">
                  <a href="https://github.com/Teradata/jupyter-demos/issues">request</a>
                  <a href="https://github.com/Teradata/jupyter-demos">contribute</a>
                </td>
                </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>


<style>
.call-to-action {
  margin-top: 20px;
}

@media screen and (max-width: 576px) {
  .call-to-action .call-to-action-button,
  .call-to-action .call-to-action-button-secondary {
    width: 100%;
  }
}

@media screen and (max-width: 820px) {
  .call-to-action {
    background-image: none;
  }

  .call-to-action-text .short-description {
    width: 100%;
  }

  .doc .admonitionblock.question.landing-page  {
    display: none;
  }

  .footer {
    display: none;
  }
}

@media screen and (min-width: 820px) {
  .call-to-action {
    background-image: url('{{uiRootPath}}/img/illustration.svg');
  }

  .call-to-action-text .short-description {
    width: 50%;
  }

  .doc .admonitionblock.question.landing-page  {
    display: inherit;
  }

  .footer {
    display: inherit;
  }
}

@media screen and (min-width: 1024px) {
  .call-to-action {
    margin-top: 48px;
  }
}

.landing-container {
  margin-left: 16px;
  margin-right: 16px;
  max-width: 1200px;
  width: 100%;
}

.landing {
  display: flex;
  width: 100%;
  justify-content: center;
}

.call-to-action {
  background-color: rgba(133, 221, 220, 0.1);
  border: 1px solid rgba(0, 0, 0, 0.12);
  box-sizing: border-box;
  border-radius: 8px;
  width: 100%;
  min-height: 241px;
  background-repeat: no-repeat;
  background-position: right top;
  background-origin: content-box;
  padding: 0px 10px 0px 10px;
}

.call-to-action-text {
  padding: 40px 30px 40px 30px;
}

.call-to-action-text .header {
  font-family: Arial, helvetica, sans-serif;
  font-size: 20px;
  line-height: 28px;
  letter-spacing: 0.15px;
  color: rgba(0, 0, 0, 0.87);
}

.call-to-action-text .short-description {
  font-family: Arial, helvetica, sans-serif;
  font-style: normal;
  font-weight: normal;
  font-size: 16px;
  line-height: 20px;
  color: rgba(0, 0, 0, 0.6);
  padding-top: 4px;
}

.search-input-container {
  width: 100%;
  margin-top: 20px;
}

.search-input-container #search-input {
  font-family: Arial, helvetica, sans-serif;
  width: 100%;
}

.tile-container {
  padding: 0px;
  width: 100%;
  margin: auto;
}

.tile-container .title {
  font-family: RidleyGrotesk, Arial, Helvetica, sans-serif;
  font-size: 48px;
  line-height: 64px;
  color: rgba(0, 0, 0, 0.87);
}

.tile-section-title {
  font-family: RidleyGrotesk, Arial, Helvetica, sans-serif;
  font-style: normal;
  font-weight: 600;
  font-size: 20px;
  line-height: 28px;
  letter-spacing: 0.15px;
  color: rgba(0, 0, 0, 0.87);
  padding-top: 24px;
  scroll-margin-top: 110px;
  scroll-snap-margin: 110px;
}

.tile {
  min-height: 188px;
  background: #FFFFFF;
  box-shadow: 0px 0px 2px rgba(0, 0, 0, 0.14), 0px 2px 2px rgba(0, 0, 0, 0.12), 0px 1px 3px rgba(0, 0, 0, 0.2);
  border-radius: 8px;
  position: relative;
}

.tile:hover {
  box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.14), 0px 4px 5px rgba(0, 0, 0, 0.12), 0px 1px 10px rgba(0, 0, 0, 0.2);
}

.tile .link {
  width: 100%;
  height: 100%;
  padding: 16px;
}

@media screen and (min-width: 580px) {
  .tile-section-container.source-code {
    grid-template-columns: repeat(auto-fit, minmax(470px, 1fr));
  }
}

@media screen and (max-width: 580px) {
  .tile-section-container.source-code {
    grid-template-columns: repeat(auto-fit, minmax(270px, 1fr));
  }
}

.tile-section-container.source-code {
  display: grid;
  grid-column-gap: 30px;
  grid-row-gap: 20px;
  padding-top: 8px;
}

.tile a:hover {
  text-decoration: none;
}

.tile-section-container {
  display: grid;
  grid-column-gap: 30px;
  grid-row-gap: 20px;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  padding-top: 8px;
}

.tile-title,
.tile-tags {
  font-family: Arial, helvetica, sans-serif;
  font-style: normal;
  font-weight: normal;
  font-size: 16px;
  line-height: 20px;
  color: rgba(0, 0, 0, 0.87);
}

.tile-content {
  font-family: Arial, helvetica, sans-serif;
  font-style: normal;
  font-weight: normal;
  font-size: 14px;
  line-height: 20px;
  letter-spacing: 0.25px;
  color: rgba(0, 0, 0, 0.6);
  margin-top: 16px;
  margin-bottom: 50px;
}

.tag {
  background: #E0E0E0;
  border-radius: 16px;
  font-family: Arial;
  font-style: normal;
  font-weight: normal;
  font-size: 14px;
  line-height: 20px;
  padding: 6px 12px;
  width: fit-content;
}

.tile-tags {
  position: absolute;
  bottom: 16px;
}

.tile-action {
  font-family: RidleyGrotesk, Arial, Helvetica, sans-serif;
  font-size: 14px;
  line-height: 16px;
  letter-spacing: 0.5px;
  text-transform: uppercase;
  color: #007373;
  border: 1px #007373 solid;
  border-radius: 8px;
  padding: 9px 8px;
  position: absolute;
  bottom: 24px;
  right: 24px;
}

.call-to-action-button {
  background: #007373;
  box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.14), 0px 3px 4px rgba(0, 0, 0, 0.12), 0px 1px 5px rgba(0, 0, 0, 0.2);
  border-radius: 8px;
  text-transform: uppercase;
  text-decoration: none;
  font-family: RidleyGrotesk, Arial, Helvetica, sans-serif;
  font-size: 14px;
  line-height: 16px;
  letter-spacing: 0.5px;
  text-align: center;
  text-transform: uppercase;
  color: rgba(255, 255, 255, 0.87);
  padding: 11px 12px;
  margin-right: 16px;
  display: inline-block;
}

.button-container {
  margin-top: 15px;
}

.call-to-action-button:hover {
  text-decoration: none;
}

.call-to-action-button-secondary {
  border: 1px solid rgba(0, 0, 0, 0.6);
  box-sizing: border-box;
  border-radius: 8px;
  text-transform: uppercase;
  text-decoration: none;
  font-family: RidleyGrotesk, Arial, Helvetica, sans-serif;
  font-size: 14px;
  line-height: 16px;
  letter-spacing: 0.5px;
  text-align: center;
  text-transform: uppercase;
  color: rgba(0, 0, 0, 0.87);
  padding: 11px 12px;
  margin-top: 15px;
  background: #eaf2f2;
  display: inline-block;
}

.call-to-action-button-secondary:hover {
  text-decoration: none;
}

.search-result-dropdown-menu {
  top: initial;
  right: initial;
  max-width: 60%;
}

.tile-container .doc {
  padding: 0px;
  margin: 0px;
}

.doc .admonitionblock.question.landing-page .icon {
  text-transform: initial;
}

.question-action {
  width: 280px;
  font-family: RidleyGrotesk, Arial, Helvetica, sans-serif;
  font-size: 14px;
  line-height: 16px;
  letter-spacing: 0.5px;
  text-transform: uppercase;
}

.question-action a {
  color: rgba(0, 0, 0, 0.87);
  padding: 0px 20px;
}

.question-action a:hover {
  color: #f3743f;
  text-decoration: none;
}

.doc .admonitionblock.landing-page td.content {
  width: 80%;
}

div.tile-icons {
  position: absolute;
  bottom: 24px;
  left: 16px;
  display: flex;
}

.tile-icons img {
  height: 34px;
  width: 34px;
  margin: 0px 8px 0px 0px;
}

.alternate-action {
  font-size: 14px;
  margin-top: 20px;
}

.alternate-action a {
  color: #007373;
}

.alternate-action a:hover {
  text-decoration: none;
}
</style>
++++
