= Crear archivos Parquet en el almacenamiento de objetos
:page-lang: es
:experimental:
:page-author: Obed Vega
:page-email: obed.vega@teradata.com
:page-revdate: 2 de agosto de 2022
:description: Teradata Vantage Native Object Storage: lectura y escritura desde/hacia el almacenamiento de objetos, interfaz SQL unificada para Vantage y almacenamiento de objetos.
:keywords: almacenes de datos, separación de almacenamiento informático, Teradata, vantage, plataforma de datos en la nube, almacenamiento de objetos, inteligencia empresarial, análisis empresarial, parquet, creación de archivos parquet

== Descripción general
Native Object Storage (NOS) es una función de Vantage que le permite consultar datos almacenados en archivos como conjuntos de datos en formato CSV, JSON y Parquet.
Estos conjuntos de datos se encuentran en un almacenamiento de objetos externo compatible con S3, como AWS S3, Google GCS, Azure Blob o implementaciones locales.
Es útil en escenarios en los que desea explorar datos sin crear una canalización de datos para incorporarlos a Vantage. Este tutorial demuestra cómo exportar datos desde Vantage al almacenamiento de objetos utilizando el formato de archivo Parquet.

== Requisitos previos

Necesita acceso a una instancia de Teradata Vantage. NOS está habilitado en todas las ediciones de Vantage, desde Vantage Express hasta Developer, DYI y Vantage as a Service a partir de la versión 17.10.

IMPORTANT: Este tutorial se basa en el almacenamiento de objetos de s3 aws. Necesitará su propio depósito s3 con permisos de escritura para completar el tutorial.

include::../partials/vantage_clearscape_analytics.adoc[]

== Crear un archivo Parquet con la función WRITE_NOS

`WRITE_NOS` le permite extraer columnas seleccionadas o todas de una tabla de base de datos o de resultados derivados y escribir en un almacenamiento de objetos externo, como Amazon S3, Azure Blob Storage, Azure Data Lake Storage Gen2 y Google Cloud Storage. Esta funcionalidad almacena datos en formato Parquet.

Puede encontrar más documentación sobre la funcionalidad `WRITE_NOS` en la https://docs.teradata.com/r/Teradata-VantageTM-Native-Object-Store-Getting-Started-Guide/June-2022/Writing-Data-to-External-Object-Store[documentación de NOS].

Necesitará acceso a una base de datos donde pueda ejecutar la función `WRITE_NOS`. Si no tiene dicha base de datos, ejecute los siguientes comandos:
[source, teradata-sql, id="parquet_create_user", role="emits-gtm-events"]
----
CREATE USER db AS PERM=10e7, PASSWORD=db;

-- Don't forget to give the proper access rights
GRANT EXECUTE FUNCTION on TD_SYSFNLIB.READ_NOS to db;
GRANT EXECUTE FUNCTION on TD_SYSFNLIB.WRITE_NOS to db;
----

NOTE: Si desea obtener más información sobre cómo configurar usuarios y sus privilegios, consulte la https://docs.teradata.com/r/Teradata-VantageTM-Native-Object-Store-Getting-Started-Guide/June-2022/Setting-Up-Access/Setting-Access-Privileges[documentación de NOS].


1. Primero creemos una tabla en su instancia de Teradata Vantage:
+
[source, teradata-sql]
----
CREATE SET TABLE db.parquet_table ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      column1 SMALLINT NOT NULL,
      column2 DATE FORMAT 'YY/MM/DD' NOT NULL,
      column3 DECIMAL(10,2))
PRIMARY INDEX ( column1 );
----

2. Complete su tabla con datos de ejemplo:
+
[source, teradata-sql]
----
INSERT INTO db.parquet_table (1,'2022/01/01',1.1);
INSERT INTO db.parquet_table (2,'2022/01/02',2.2);
INSERT INTO db.parquet_table (3,'2022/01/03',3.3);
----
+
Su tabla ahora debería verse así:
+
----
column1   column2       column3
-------  --------  ------------
      1  22/01/01          1.10
      2  22/01/02          2.20
      3  22/01/03          3.30
----

3. Cree el archivo parquet con `WRITE_NOS`. No olvide reemplazar `<BUCKET_NAME>` con el nombre de su depósito s3. Además, reemplace `<YOUR-ACCESS-KEY-ID>` y `<YOUR-SECRET-ACCESS-KEY>` con su clave de acceso y secreto.
+
NOTE: Consulte los documentos de su proveedor de nube sobre cómo crear credenciales para acceder al almacenamiento de objetos. Por ejemplo, para AWS consulte https://aws.amazon.com/premiumsupport/knowledge-center/create-access-key/[¿Cómo creo una clave de acceso de AWS?]
+
[source, teradata-sql]
----
SELECT * FROM WRITE_NOS (
ON ( SELECT * FROM db.parquet_table)
USING
LOCATION('/s3/<BUCKET_NAME>.s3.amazonaws.com/parquet_file_on_NOS.parquet')
AUTHORIZATION('{"ACCESS_ID":"<YOUR-ACCESS-KEY-ID>",
"ACCESS_KEY":"<YOUR-SECRET-ACCESS-KEY>"}')
STOREDAS('PARQUET')
MAXOBJECTSIZE('16MB')
COMPRESSION('SNAPPY')
INCLUDE_ORDERING('TRUE')
INCLUDE_HASHBY('TRUE')
) as d;
----
+
Ahora ha creado un archivo parquet en su depósito de almacenamiento de objetos. Ahora, para consultar fácilmente su archivo, debe seguir el paso número 4.

4. Cree una tabla externa respaldada por NOS. No olvide reemplazar `<BUCKET_NAME>` con el nombre de su depósito s3. Además, reemplace `<YOUR-ACCESS-KEY-ID>` y `<YOUR-SECRET-ACCESS-KEY>` con su clave de acceso y secreto:
+
[source, teradata-sql]
----
CREATE MULTISET FOREIGN TABLE db.parquet_table_to_read_file_on_NOS
, EXTERNAL SECURITY DEFINER TRUSTED CEPH_AUTH,
MAP = TD_MAP1
(
  Location VARCHAR(2048) CHARACTER SET UNICODE CASESPECIFIC
  , col1 SMALLINT
  , col2 DATE
  , col3 DECIMAL(10,2)

)
USING (
    LOCATION ('/s3/<BUCKET_NAME>.s3.amazonaws.com/parquet_file_on_NOS.parquet')
    AUTHORIZATION('{"ACCESS_ID":"<YOUR-ACCESS-KEY-ID>",
    "ACCESS_KEY":"<YOUR-SECRET-ACCESS-KEY>"}')
    STOREDAS ('PARQUET')
)NO PRIMARY INDEX;
----

5. Ahora que está listo para consultar su archivo parquet en NOS, intentemos la siguiente consulta:
+
[source, teradata-sql]
----
SELECT col1, col2, col3 FROM db.parquet_table_to_read_file_on_NOS;
----
+
Los datos devueltos por la consulta deberían verse así:
+
----
  col1      col2          col3
------  --------  ------------
     1  22/01/01          1.10
     2  22/01/02          2.20
     3  22/01/03          3.30
----

== Resumen

En este tutorial, hemos aprendido cómo exportar datos de Vantage a un archivo parquet en el almacenamiento de objetos utilizando Native Object Storage (NOS). NOS admite la lectura e importación de datos almacenados en formatos CSV, JSON y Parquet. NOS también puede exportar datos desde Vantage al almacenamiento de objetos.

== Otras lecturas
* link:https://docs.teradata.com/r/Teradata-VantageTM-Native-Object-Store-Getting-Started-Guide/June-2022/Writing-Data-to-External-Object-Store[Teradata Vantage™: escritura de datos en un almacén de objetos externo]

include::../partials/community_link.adoc[]