= dbt con Teradata Vantage
:page-lang: es
:experimental:
:page-author: Adam Tworkiewicz
:page-email: adam.tworkiewicz@teradata.com
:page-revdate: 12 de julio de 2023
:description: Utilice dbt (herramienta de creación de datos) con Teradata Vantage.
:keywords: almacenes de datos, separación de almacenamiento informático, teradata, vantage, plataforma de datos en la nube, almacenamiento de objetos, inteligencia empresarial, análisis empresarial, elt, dbt.
:tabs:

== Descripción general

Este tutorial demuestra cómo utilizar dbt (Herramienta de creación de datos) con Teradata Vantage. Está basado en el link:https://github.com/dbt-labs/jaffle_shop-dev[tutorial original de dbt Jaffle Shop]. Se han ajustado un par de modelos al dialecto SQL admitido por Vantage.

== Requisitos previos

* Acceso a una instancia de Teradata Vantage.
+
include::../partials/vantage_clearscape_analytics.adoc[]
* Python *3.7*, *3.8*, *3.9*, *3.10* o *3.11* instalado.

== Instalar dbt

1. Clone el repositorio del tutorial y use cd para ir al directorio del proyecto:
+
[source, bash]
----
git clone https://github.com/Teradata/jaffle_shop-dev.git jaffle_shop
cd jaffle_shop
----
2. Cree un nuevo entorno Python para administrar dbt y sus dependencias. Active el entorno:
+
[tabs]
====
Windows::
+
--
[source, bash]
----
python -m venv env
source env/Scripts/activate
----
--
MacOS::
+
--
[source, bash]
----
python3 -m venv env
source env/bin/activate
----
--
Linux::
+
--
[source, bash]
----
python3 -m venv env
source env/bin/activate
----
--
====

3. Instale el módulo `dbt-teradata` y sus dependencias. El módulo dbt principal se incluye como una dependencia, por lo que no es necesario instalarlo por separado:
+
[source, bash]
----
pip install dbt-teradata
----

== Configurar dbt

Ahora configuraremos dbt para conectarse a su base de datos Vantage. Cree el archivo `$HOME/.dbt/profiles.yml` con el siguiente contenido. Ajuste `<host>`, `<user>`, `<password>` para que coincida con su instancia de Teradata.

[NOTE]
.Configuración de la base de datos
====
El siguiente perfil dbt apunta a una base de datos llamada `jaffle_shop`. Si la base de datos no existe en su instancia de Teradata Vantage, se creará. También puede cambiar el valor `schema` para que apunte a una base de datos existente en su instancia.
====

[source, yaml, id="dbt_first_config", role="emits-gtm-events"]
----
jaffle_shop:
  outputs:
    dev:
      type: teradata
      host: <host>
      user: <user>
      password: <password>
      logmech: TD2
      schema: jaffle_shop
      tmode: ANSI
      threads: 1
      timeout_seconds: 300
      priority: interactive
      retries: 1
  target: dev
----

Ahora que tenemos el archivo de perfil en su lugar, podemos validar la configuración:

[source, bash]
----
dbt debug
----

Si el comando de depuración devolvió errores, es probable que tenga un problema con el contenido de `profiles.yml`.

== Acerca del almacén de Jaffle Shop

`jaffle_shop` es una tienda de comercio electrónico ficticia. Este proyecto dbt transforma datos sin procesar de la base de datos de una aplicación en un modelo dimensional con datos de clientes y pedidos listos para análisis.

Los datos sin procesar de la aplicación consisten en clientes, pedidos y pagos, con el siguiente diagrama entidad-relación:

[erd, format=svg, width=100%]
....
# Entities

[customers] {bgcolor: "#f37843", color: "#ffffff", border: "0", border-color: "#ffffff"}
  *`id  ` {bgcolor: "#f9d6cd", color: "#000000", label: "int", border: "1", border-color: "#ffffff"}
  `first_name  ` {bgcolor: "#fcece8", color: "#868686", label: "varchar", border: "1", border-color: "#ffffff"}
  `last_name  ` {bgcolor: "#fcece8", color: "#868686", label: "varchar", border: "1", border-color: "#ffffff"}
  `email  ` {bgcolor: "#fcece8", color: "#868686", label: "varchar", border: "1", border-color: "#ffffff"}

[orders] {bgcolor: "#f37843", color: "#ffffff", border: "0", border-color: "#ffffff"}
  *`id  ` {bgcolor: "#f9d6cd", color: "#000000", label: "int", border: "1", border-color: "#ffffff"}
  +`user_id  ` {bgcolor: "#fcece8", color: "#868686", label: "int", border: "1", border-color: "#ffffff"}
  `order_date  ` {bgcolor: "#fcece8", color: "#868686", label: "date", border: "1", border-color: "#ffffff"}
  `status  ` {bgcolor: "#fcece8", color: "#868686", label: "varchar", border: "1", border-color: "#ffffff"}

[payments] {bgcolor: "#f37843", color: "#ffffff", border: "0", border-color: "#ffffff"}
  *`id  ` {bgcolor: "#f9d6cd", color: "#000000", label: "int", border: "1", border-color: "#ffffff"}
  +`order_id  ` {bgcolor: "#fcece8", color: "#868686", label: "int", border: "1", border-color: "#ffffff"}
  `payment_method  ` {bgcolor: "#fcece8", color: "#868686", label: "int", border: "1", border-color: "#ffffff"}
  `amount  ` {bgcolor: "#fcece8", color: "#868686", label: "int", border: "1", border-color: "#ffffff"}

# Relationships

customers   1--* orders
orders      1--* payments
....

dbt toma esta tabla de datos sin procesar y construye el siguiente modelo dimensional, que es más adecuado para herramientas de análisis:
[erd, format=svg, width=100%]
....
# Entities

[`dimension: customers`] {bgcolor: "#f37843", color: "#ffffff", border: "0", border-color: "#ffffff"}
  *`customer_id  ` {bgcolor: "#f9d6cd", color: "#000000", label: "int", border: "1", border-color: "#ffffff"}
  `first_name  ` {bgcolor: "#fcece8", color: "#868686", label: "varchar", border: "1", border-color: "#ffffff"}
  `last_name  ` {bgcolor: "#fcece8", color: "#868686", label: "varchar", border: "1", border-color: "#ffffff"}
  `email  ` {bgcolor: "#fcece8", color: "#868686", label: "varchar", border: "1", border-color: "#ffffff"}
  `first_order  ` {bgcolor: "#fcece8", color: "#868686", label: "date", border: "1", border-color: "#ffffff"}
  `most_recent_order  ` {bgcolor: "#fcece8", color: "#868686", label: "date", border: "1", border-color: "#ffffff"}
  `number_of_orders  ` {bgcolor: "#fcece8", color: "#868686", label: "int", border: "1", border-color: "#ffffff"}
  `total_order_amount  ` {bgcolor: "#fcece8", color: "#868686", label: "int", border: "1", border-color: "#ffffff"}

[`fact: orders`] {bgcolor: "#f37843", color: "#ffffff", border: "0", border-color: "#ffffff"}
  *`order_id  ` {bgcolor: "#f9d6cd", color: "#000000", label: "int", border: "1", border-color: "#ffffff"}
  +`customer_id  ` {bgcolor: "#fcece8", color: "#868686", label: "int", border: "1", border-color: "#ffffff"}
  `order_date  ` {bgcolor: "#fcece8", color: "#868686", label: "date", border: "1", border-color: "#ffffff"}
  `status  ` {bgcolor: "#fcece8", color: "#868686", label: "varchar", border: "1", border-color: "#ffffff"}
  `amount  ` {bgcolor: "#fcece8", color: "#868686", label: "int", border: "1", border-color: "#ffffff"}
  `credit_card_amount  ` {bgcolor: "#fcece8", color: "#868686", label: "int", border: "1", border-color: "#ffffff"}
  `coupon_amount  ` {bgcolor: "#fcece8", color: "#868686", label: "int", border: "1", border-color: "#ffffff"}
  `bank_transfer_amount  ` {bgcolor: "#fcece8", color: "#868686", label: "int", border: "1", border-color: "#ffffff"}
  `gift_card_amount  ` {bgcolor: "#fcece8", color: "#868686", label: "int", border: "1", border-color: "#ffffff"}

# Relationships
`dimension: customers`   1--* `fact: orders`
....

== Ejecutar dbt

=== Crear tablas de datos sin procesar

En la vida real, obtendremos datos sin procesar de plataformas como Segment, Stitch, Fivetran u otra herramienta ETL. En nuestro caso, usaremos la funcionalidad `seed` de dbt para crear tablas a partir de archivos csv. Los archivos csv se encuentran en el directorio `./data`. Cada archivo csv producirá una tabla. dbt, inspeccionará los archivos y realizará inferencias de tipos para decidir qué tipos de datos utilizar para las columnas.

Creemos las tablas de datos sin procesar:
[source, bash]
----
dbt seed
----

Ahora debería ver 3 tablas en su base de datos `jaffle_shop`: `raw_customers`, `raw_orders`, `raw_payments`. Las tablas deben completarse con datos de los archivos csv.

=== Crear el modelo dimensional

Ahora que tenemos las tablas sin formato, podemos indicarle a dbt que cree el modelo dimensional:
[source, bash]
----
dbt run
----

Entonces, ¿qué pasó exactamente aquí? dbt creó tablas adicionales usando `CREATE TABLE/VIEW FROM SELECT` SQL. En la primera transformación, dbt tomó tablas sin procesar y creó tablas de unión desnormalizadas llamadas `customer_orders`, `order_payments`, `customer_payments`. Encontrará las definiciones de estas tablas en `./marts/core/intermediate`.
En el segundo paso, dbt creó las tablas `dim_customers` y `fct_orders`. Estas son las tablas del modelo dimensional que queremos exponer a nuestra herramienta de BI.

=== Probar los datos

dbt aplicó múltiples transformaciones a nuestros datos. ¿Cómo podemos asegurarnos de que los datos del modelo dimensional sean correctos? dbt nos permite definir y ejecutar pruebas con los datos. Las pruebas están definidas en `./marts/core/schema.yml`. El archivo describe cada columna en todas las relaciones. Cada columna puede tener varias pruebas configuradas en la llave `tests`. Por ejemplo, esperamos que la columna `fct_orders.order_id` contenga valores únicos y no nulos. Para validar que los datos en las tablas creadas satisfacen las condiciones de prueba, ejecute:

[source, bash]
----
dbt test
----

=== Generar documentación

Nuestro modelo consta de unas pocas tablas. Imagine un escenario en el que tengamos muchas más fuentes de datos y un modelo dimensional mucho más complejo. También podríamos tener una zona intermedia entre los datos brutos y el modelo dimensional que sigue los principios de Data Vault 2.0. ¿No sería útil si tuviéramos las entradas, transformaciones y salidas documentadas de alguna manera? dbt nos permite generar documentación a partir de sus archivos de configuración:

[source, bash]
----
dbt docs generate
----

Esto generará archivos html en el directorio `./target`.

Puede iniciar su propio servidor para explorar la documentación. El siguiente comando iniciará un servidor y abrirá una pestaña del navegador con la página de inicio de los documentos:

[source, bash]
----
dbt docs serve
----

== Resumen

Este tutorial demostró cómo usar dbt con Teradata Vantage. El proyecto de muestra toma datos sin procesar y genera un data mart dimensional. Usamos múltiples comandos dbt para completar tablas a partir de archivos csv (`dbt seed`), crear modelos (`dbt run`), probar los datos (`dbt test`) y generar y entregar documentación del modelo (`dbt docs generate`, `dbt docs serve`).

== Otras lecturas
* link:https://docs.getdbt.com/docs/[Documentación de dbt]
* link:https://github.com/Teradata/dbt-teradata[Documentación del complemento dbt-teradata]

include::../partials/community_link.adoc[]
