
= Teradata Connector - Mule 4

Anypoint Connector for Teradata (Teradata Connector) establishes communication between your Mule app and a Teradata Vantage database, enabling you to connect with your Teradata Vantage instance to load data and run SQL queries in Teradata Vantage tables.

Reference: xref:reference.adoc[Teradata Connector Reference]

Release Notes: xref:release-notes.adoc[Teradata Connector Release Notes]

== Before You Begin

To use this connector, you must be familiar with:

* Teradata Vantage SQL
* Anypoint Connectors
* Mule runtime engine (Mule)
* Elements and global elements in a Mule flow
* Creating a Mule app using Anypoint Studio (Studio)

Before creating an app, you must have:

* Credentials to access the Teradata Vantage target resource
* Anypoint Studio version 7.5 or later

== Common Use Cases for the Connector

Teradata Connector enables you to:

* Perform predefined queries, dynamically constructed queries, and template queries that are self-sufficient and customizable.
* Use a source listener operation to read from a database in the data source section of a flow.
* Execute other operations to read and write to a database anywhere in the process section.
* Run a single bulk update to perform multiple SQL requests.
* Make Data Definition Language (DDL) requests.
* Execute stored procedures and SQL scripts.


== Next Step

// After you complete the prerequisites and try the templates and examples, you are ready to create your own app and configure the connector using Anypoint Studio.

== See Also
https://help.mulesoft.com[MuleSoft Help Center]
