name: CI
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 17
          cache: npm
      - name: Run Antora
        run: ./buildw
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          preview-branch: gh-pages
          source-dir: build/site
          umbrella-dir: pr-preview
